name: PHP Linting 
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: michaelw90/PHP-Lint@master

