name: PHPLint 
on: pull_request

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: michaelw90/PHP-Lint@master

